export const LAY_DANH_SACH_DANH_MUC = 'LAY_DANH_SACH_DANH_MUC';

export const LAY_DANH_SACH_KHOA_HOC_THEO_DANH_MUC = 'LAY_DANH_SACH_KHOA_HOC_THEO_DANH_MUC';

export const LAY_CHI_TIET_KHOA_HOC = 'LAY_CHI_TIET_KHOA_HOC'