export const LAY_DANH_SACH_KHOA_HOC = 'LAY_DANH_SACH_KHOA_HOC'; 

export const TIM_KIEM_KHOA_HOC = 'TIM_KIEM_KHOA_HOC'; 

export const LAY_CHI_TIET_KHOA_HOC = 'LAY_CHI_TIET_KHOA_HOC'; 

export const LAY_DANH_MUC_KHOA_HOC = 'LAY_DANH_MUC_KHOA_HOC'; 

export const LAY_KHOA_HOC_THEO_DANH_MUC = 'LAY_KHOA_HOC_THEO_DANH_MUC'; 

export const THEM_VAO_GIO_HANG = 'THEM_VAO_GIO_HANG'; 

export const DANG_KY_HOC = 'DANG_KY_HOC'; 

export const HUY_DANG_KY_HOC = 'HUY_DANG_KY_HOC'; 

export const DANG_KY = 'DANG_KY'; 

export const DANG_NHAP = 'DANG_NHAP'; 

export const DANG_XUAT = 'DANG_XUAT';

export const XEM_THONG_TIN_CA_NHAN = 'XEM_THONG_TIN_CA_NHAN';

export const SUA_THONG_TIN_CA_NHAN = 'SUA_THONG_TIN_CA_NHAN';


// ============================================================= QUẢN TRỊ ======================================

// QUẢN TRỊ NG DÙNG
export const TIM_KIEM_NGUOI_DUNG = 'TIM_KIEM_NGUOI_DUNG';

export const XEM_THONG_TIN_SUA = 'XEM_THONG_TIN_SUA';

export const CAP_NHAT_NGUOI_DUNG = 'CAP_NHAT_NGUOI_DUNG';

export const LAY_DANH_SACH_KHOA_HOC_DA_XET_DUYET = 'LAY_DANH_SACH_KHOA_HOC_DA_XET_DUYET';

export const LAY_DANH_SACH_KHOA_HOC_CHO_XET_DUYET = 'LAY_DANH_SACH_KHOA_HOC_CHO_XET_DUYET';

export const LAY_DANH_SACH_KHOA_HOC_CHUA_GHI_DANH = 'LAY_DANH_SACH_KHOA_HOC_CHUA_GHI_DANH';

export const DANG_KY_KHOA_HOC = 'DANG_KY_KHOA_HOC';

export const HUY_DANG_KY_KHOA_HOC = 'HUY_DANG_KY_KHOA_HOC';

//QUẢN TRỊ KHÓA HỌC
export const THEM_KHOA_HOC = 'THEM_KHOA_HOC';

export const XOA_KHOA_HOC = 'XOA_KHOA_HOC';

export const SUA_KHOA_HOC = 'SUA_KHOA_HOC';

export const CAP_NHAT_KHOA_HOC = 'CAP_NHAT_KHOA_HOC';

export const LAY_DANH_SACH_NGUOI_DUNG_DA_XET_DUYET = 'LAY_DANH_SACH_NGUOI_DUNG_DA_XET_DUYET';

export const LAY_DANH_SACH_NGUOI_DUNG_CHO_XET_DUYET = 'LAY_DANH_SACH_NGUOI_DUNG_CHO_XET_DUYET';

export const LAY_DANH_SACH_NGUOI_DUNG_CHUA_GHI_DANH = 'LAY_DANH_SACH_NGUOI_DUNG_CHUA_GHI_DANH';

export const GHI_DANH_NGUOI_DUNG = 'GHI_DANH_NGUOI_DUNG';

export const HUY_GHI_DANH_NGUOI_DUNG = 'HUY_GHI_DANH_NGUOI_DUNG'

export const DANG_KY_NGUOI_DUNG = 'DANG_KY_NGUOI_DUNG'