export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';

export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';

export const XOA_NGUOI_DUNG = 'XOA_NGUOI_DUNG';

export const TIM_KIEM_NGUOI_DUNG_LOC = 'TIM_KIEM_NGUOI_DUNG_LOC'