export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';

export const XOA_NGUOI_DUNG = 'XOA_NGUOI_DUNG';

export const TUY_CHINH_NGUOI_DUNG = 'TUY_CHINH_NGUOI_DUNG';

export const LAY_DANH_SACH_NGUOI_DUNG_TUY_CHON = 'LAY_DANH_SACH_NGUOI_DUNG_TUY_CHON';

export const PHAN_TRANG_NGUOI_DUNG = 'PHAN_TRANG_NGUOI_DUNG'